// SPDX-License-Identifier: GPL-2.0+

#include <kunit/test.h>

#include <drm/drm_fixed.h>
#include <drm/drm_fourcc.h>

#include "../castkms_formats.h"

#define TEST_BUFF_SIZE 50

MODULE_IMPORT_NS("EXPORTED_FOR_KUNIT_TESTING");

/**
 * struct pixel_yuv_u16 - Internal representation of a pixel color.
 * @y: Luma value, stored in 16 bits, without padding, using
 *     machine endianness
 * @u: Blue difference chroma value, stored in 16 bits, without padding, using
 *     machine endianness
 * @v: Red difference chroma value, stored in 16 bits, without padding, using
 *     machine endianness
 */
struct pixel_yuv_u16 {
	u16 y, u, v;
};

/*
 * struct yuv_u16_to_argb_u16_case - Reference values to test the color
 * conversions in CASTKMS between YUV to ARGB
 *
 * @encoding: Encoding used to convert RGB to YUV
 * @range: Range used to convert RGB to YUV
 * @n_colors: Count of test colors in this case
 * @format_pair.name: Name used for this color conversion, used to
 *                    clarify the test results
 * @format_pair.rgb: RGB color tested
 * @format_pair.yuv: Same color as @format_pair.rgb, but converted to
 *                   YUV using @encoding and @range.
 */
struct yuv_u16_to_argb_u16_case {
	enum drm_color_encoding encoding;
	enum drm_color_range range;
	size_t n_colors;
	struct format_pair {
		char *name;
		struct pixel_yuv_u16 yuv;
		struct pixel_argb_u16 argb;
	} colors[TEST_BUFF_SIZE];
};

/*
 * The YUV color representation were acquired via the colour python framework.
 * Below are the function calls used for generating each case.
 *
 * For more information got to the docs:
 * https://colour.readthedocs.io/en/master/generated/colour.RGB_to_YCbCr.html
 */
static struct yuv_u16_to_argb_u16_case yuv_u16_to_argb_u16_cases[] = {
	/*
	 * colour.RGB_to_YCbCr(<rgb color in 16 bit form>,
	 *                     K=colour.WEIGHTS_YCBCR["ITU-R BT.601"],
	 *                     in_bits = 16,
	 *                     in_legal = False,
	 *                     in_int = True,
	 *                     out_bits = 16,
	 *                     out_legal = False,
	 *                     out_int = True)
	 *
	 * Tests cases for color conversion generated by converting RGB
	 * values to YUV BT601 full range using the ITU-R BT.601 weights.
	 */
	{
		.encoding = DRM_COLOR_YCBCR_BT601,
		.range = DRM_COLOR_YCBCR_FULL_RANGE,
		.n_colors = 6,
		.colors = {
			{ "white", { 0xffff, 0x8000, 0x8000 }, { 0xffff, 0xffff, 0xffff, 0xffff }},
			{ "gray",  { 0x8080, 0x8000, 0x8000 }, { 0xffff, 0x8080, 0x8080, 0x8080 }},
			{ "black", { 0x0000, 0x8000, 0x8000 }, { 0xffff, 0x0000, 0x0000, 0x0000 }},
			{ "red",   { 0x4c8b, 0x54ce, 0xffff }, { 0xffff, 0xffff, 0x0000, 0x0000 }},
			{ "green", { 0x9645, 0x2b33, 0x14d1 }, { 0xffff, 0x0000, 0xffff, 0x0000 }},
			{ "blue",  { 0x1d2f, 0xffff, 0x6b2f }, { 0xffff, 0x0000, 0x0000, 0xffff }},
		}
	},
	/*
	 * colour.RGB_to_YCbCr(<rgb color in 16 bit form>,
	 *                     K=colour.WEIGHTS_YCBCR["ITU-R BT.601"],
	 *                     in_bits = 16,
	 *                     in_legal = False,
	 *                     in_int = True,
	 *                     out_bits = 16,
	 *                     out_legal = True,
	 *                     out_int = True)
	 * Tests cases for color conversion generated by converting RGB
	 * values to YUV BT601 limited range using the ITU-R BT.601 weights.
	 */
	{
		.encoding = DRM_COLOR_YCBCR_BT601,
		.range = DRM_COLOR_YCBCR_LIMITED_RANGE,
		.n_colors = 6,
		.colors = {
			{ "white", { 0xeb00, 0x8000, 0x8000 }, { 0xffff, 0xffff, 0xffff, 0xffff }},
			{ "gray",  { 0x7dee, 0x8000, 0x8000 }, { 0xffff, 0x8080, 0x8080, 0x8080 }},
			{ "black", { 0x1000, 0x8000, 0x8000 }, { 0xffff, 0x0000, 0x0000, 0x0000 }},
			{ "red",   { 0x517b, 0x5a34, 0xf000 }, { 0xffff, 0xffff, 0x0000, 0x0000 }},
			{ "green", { 0x908e, 0x35cc, 0x2237 }, { 0xffff, 0x0000, 0xffff, 0x0000 }},
			{ "blue",  { 0x28f7, 0xf000, 0x6dc9 }, { 0xffff, 0x0000, 0x0000, 0xffff }},
		}
	},
	/*
	 * colour.RGB_to_YCbCr(<rgb color in 16 bit form>,
	 *                     K=colour.WEIGHTS_YCBCR["ITU-R BT.709"],
	 *                     in_bits = 16,
	 *                     in_legal = False,
	 *                     in_int = True,
	 *                     out_bits = 16,
	 *                     out_legal = False,
	 *                     out_int = True)
	 * Tests cases for color conversion generated by converting RGB
	 * values to YUV BT709 full range using the ITU-R BT.709 weights.
	 */
	{
		.encoding = DRM_COLOR_YCBCR_BT709,
		.range = DRM_COLOR_YCBCR_FULL_RANGE,
		.n_colors = 6,
		.colors = {
			{ "white", { 0xffff, 0x8000, 0x8000 }, { 0xffff, 0xffff, 0xffff, 0xffff }},
			{ "gray",  { 0x8080, 0x8000, 0x8000 }, { 0xffff, 0x8080, 0x8080, 0x8080 }},
			{ "black", { 0x0000, 0x8000, 0x8000 }, { 0xffff, 0x0000, 0x0000, 0x0000 }},
			{ "red",   { 0x366d, 0x62ac, 0xffff }, { 0xffff, 0xffff, 0x0000, 0x0000 }},
			{ "green", { 0xb717, 0x1d55, 0x0bbd }, { 0xffff, 0x0000, 0xffff, 0x0000 }},
			{ "blue",  { 0x127c, 0xffff, 0x7443 }, { 0xffff, 0x0000, 0x0000, 0xffff }},
		}
	},
	/*
	 * colour.RGB_to_YCbCr(<rgb color in 16 bit form>,
	 *                     K=colour.WEIGHTS_YCBCR["ITU-R BT.709"],
	 *                     in_bits = 16,
	 *                     in_legal = False,
	 *                     in_int = True,
	 *                     out_bits = 16,
	 *                     out_legal = True,
	 *                     out_int = True)
	 * Tests cases for color conversion generated by converting RGB
	 * values to YUV BT709 limited range using the ITU-R BT.709 weights.
	 */
	{
		.encoding = DRM_COLOR_YCBCR_BT709,
		.range = DRM_COLOR_YCBCR_LIMITED_RANGE,
		.n_colors = 6,
		.colors = {
			{ "white", { 0xeb00, 0x8000, 0x8000 }, { 0xffff, 0xffff, 0xffff, 0xffff }},
			{ "gray",  { 0x7dee, 0x8000, 0x8000 }, { 0xffff, 0x8080, 0x8080, 0x8080 }},
			{ "black", { 0x1000, 0x8000, 0x8000 }, { 0xffff, 0x0000, 0x0000, 0x0000 }},
			{ "red",   { 0x3e8f, 0x6656, 0xf000 }, { 0xffff, 0xffff, 0x0000, 0x0000 }},
			{ "green", { 0xaca1, 0x29aa, 0x1a45 }, { 0xffff, 0x0000, 0xffff, 0x0000 }},
			{ "blue",  { 0x1fd0, 0xf000, 0x75bb }, { 0xffff, 0x0000, 0x0000, 0xffff }},
		}
	},
	/*
	 * colour.RGB_to_YCbCr(<rgb color in 16 bit form>,
	 *                     K=colour.WEIGHTS_YCBCR["ITU-R BT.2020"],
	 *                     in_bits = 16,
	 *                     in_legal = False,
	 *                     in_int = True,
	 *                     out_bits = 16,
	 *                     out_legal = False,
	 *                     out_int = True)
	 * Tests cases for color conversion generated by converting RGB
	 * values to YUV BT2020 full range using the ITU-R BT.2020 weights.
	 */
	{
		.encoding = DRM_COLOR_YCBCR_BT2020,
		.range = DRM_COLOR_YCBCR_FULL_RANGE,
		.n_colors = 6,
		.colors = {
			{ "white", { 0xffff, 0x8000, 0x8000 }, { 0xffff, 0xffff, 0xffff, 0xffff }},
			{ "gray",  { 0x8080, 0x8000, 0x8000 }, { 0xffff, 0x8080, 0x8080, 0x8080 }},
			{ "black", { 0x0000, 0x8000, 0x8000 }, { 0xffff, 0x0000, 0x0000, 0x0000 }},
			{ "red",   { 0x4340, 0x5c41, 0xffff }, { 0xffff, 0xffff, 0x0000, 0x0000 }},
			{ "green", { 0xad91, 0x23bf, 0x0a4c }, { 0xffff, 0x0000, 0xffff, 0x0000 }},
			{ "blue",  { 0x0f2e, 0xffff, 0x75b5 }, { 0xffff, 0x0000, 0x0000, 0xffff }},
		}
	},
	/*
	 * colour.RGB_to_YCbCr(<rgb color in 16 bit form>,
	 *                     K=colour.WEIGHTS_YCBCR["ITU-R BT.2020"],
	 *                     in_bits = 16,
	 *                     in_legal = False,
	 *                     in_int = True,
	 *                     out_bits = 16,
	 *                     out_legal = True,
	 *                     out_int = True)
	 * Tests cases for color conversion generated by converting RGB
	 * values to YUV BT2020 limited range using the ITU-R BT.2020 weights.
	 */
	{
		.encoding = DRM_COLOR_YCBCR_BT2020,
		.range = DRM_COLOR_YCBCR_LIMITED_RANGE,
		.n_colors = 6,
		.colors = {
			{ "white", { 0xeb00, 0x8000, 0x8000 }, { 0xffff, 0xffff, 0xffff, 0xffff }},
			{ "gray",  { 0x7dee, 0x8000, 0x8000 }, { 0xffff, 0x8080, 0x8080, 0x8080 }},
			{ "black", { 0x1000, 0x8000, 0x8000 }, { 0xffff, 0x0000, 0x0000, 0x0000 }},
			{ "red",   { 0x4988, 0x60b9, 0xf000 }, { 0xffff, 0xffff, 0x0000, 0x0000 }},
			{ "green", { 0xa47b, 0x2f47, 0x1902 }, { 0xffff, 0x0000, 0xffff, 0x0000 }},
			{ "blue",  { 0x1cfd, 0xf000, 0x76fe }, { 0xffff, 0x0000, 0x0000, 0xffff }},
		}
	},
};

static void castkms_format_test_init_plane(struct castkms_plane_state *plane,
					   struct castkms_frame_info *frame_info,
					   struct iosys_map *map,
					   struct drm_framebuffer *fb, u32 format)
{
	memset(plane, 0, sizeof(*plane));
	memset(frame_info, 0, sizeof(*frame_info));
	memset(map, 0, sizeof(*map) * DRM_FORMAT_MAX_PLANES);
	memset(fb, 0, sizeof(*fb));

	fb->format = drm_format_info(format);
	frame_info->fb = fb;
	frame_info->map = map;
	plane->frame_info = frame_info;
}

static void castkms_format_test_framebuffer_offset(struct kunit *test)
{
	struct castkms_plane_state plane;
	struct castkms_frame_info frame_info;
	struct iosys_map map[DRM_FORMAT_MAX_PLANES];
	struct drm_framebuffer fb;
	struct pixel_argb_u16 pixel;
	pixel_read_line_t read_line;
	u8 data[] = { 0xa5, 0x12, 0x34 };

	castkms_format_test_init_plane(&plane, &frame_info, map, &fb,
				       DRM_FORMAT_R8);
	fb.pitches[0] = 1;
	fb.offsets[0] = 1;
	iosys_map_set_vaddr(&map[0], data);

	read_line = castkms_get_pixel_read_line_function(DRM_FORMAT_R8);
	KUNIT_ASSERT_NOT_NULL(test, read_line);
	read_line(&plane, 0, 0, READ_LEFT_TO_RIGHT, 1, &pixel);

	KUNIT_EXPECT_EQ(test, pixel.a, (u16)0xffff);
	KUNIT_EXPECT_EQ(test, pixel.r, (u16)0x1212);
	KUNIT_EXPECT_EQ(test, pixel.g, (u16)0x1212);
	KUNIT_EXPECT_EQ(test, pixel.b, (u16)0x1212);
}

static void castkms_format_test_distinct_multiplane_maps(struct kunit *test)
{
	struct castkms_plane_state plane;
	struct castkms_frame_info frame_info;
	struct iosys_map map[DRM_FORMAT_MAX_PLANES];
	struct drm_framebuffer fb;
	const struct conversion_matrix *matrix = &plane.conversion_matrix;
	struct pixel_argb_u16 expected;
	struct pixel_argb_u16 pixel;
	pixel_read_line_t read_line;
	u8 luma[] = { 0xa5, 0x90, 0x10, 0x20 };
	u8 chroma[] = { 0xa5, 0xa5, 0x30, 0xd0 };

	castkms_format_test_init_plane(&plane, &frame_info, map, &fb,
				       DRM_FORMAT_NV12);
	fb.pitches[0] = 1;
	fb.pitches[1] = 2;
	fb.offsets[0] = 1;
	fb.offsets[1] = 2;
	iosys_map_set_vaddr(&map[0], luma);
	iosys_map_set_vaddr(&map[1], chroma);
	castkms_get_conversion_matrix_to_argb_u16(DRM_FORMAT_NV12,
						  DRM_COLOR_YCBCR_BT601,
						  DRM_COLOR_YCBCR_FULL_RANGE,
						  &plane.conversion_matrix);

	read_line = castkms_get_pixel_read_line_function(DRM_FORMAT_NV12);
	KUNIT_ASSERT_NOT_NULL(test, read_line);
	read_line(&plane, 0, 0, READ_LEFT_TO_RIGHT, 1, &pixel);
	expected = castkms_argb_u16_from_yuv161616(matrix, 0x9090, 0x3030, 0xd0d0);

	KUNIT_EXPECT_EQ(test, pixel.a, expected.a);
	KUNIT_EXPECT_EQ(test, pixel.r, expected.r);
	KUNIT_EXPECT_EQ(test, pixel.g, expected.g);
	KUNIT_EXPECT_EQ(test, pixel.b, expected.b);
}

static void castkms_format_test_wide_framebuffer_offset(struct kunit *test)
{
	struct castkms_plane_state plane;
	struct castkms_frame_info frame_info;
	struct iosys_map map[DRM_FORMAT_MAX_PLANES];
	struct drm_framebuffer fb;
	u64 expected;
	size_t offset;
	int rem_x, rem_y;

	castkms_format_test_init_plane(&plane, &frame_info, map, &fb,
				       DRM_FORMAT_R8);
	if (sizeof(size_t) >= sizeof(u64)) {
		fb.offsets[0] = (u32)INT_MAX + 1;
		fb.pitches[0] = (u32)INT_MAX + 2;

		offset = castkms_packed_pixels_offset(&frame_info, 3, 1, 0,
						      &rem_x, &rem_y);
		expected = (u64)fb.offsets[0] + fb.pitches[0] + 3;

		KUNIT_EXPECT_EQ(test, (u64)offset, expected);
		KUNIT_EXPECT_EQ(test, rem_x, 0);
		KUNIT_EXPECT_EQ(test, rem_y, 0);
	}
}

static void castkms_format_test_stride_range(struct kunit *test)
{
	struct drm_framebuffer fb = {};

	fb.format = drm_format_info(DRM_FORMAT_R8);
	fb.pitches[0] = U32_MAX;

	KUNIT_EXPECT_EQ(test, castkms_framebuffer_read_strides_are_valid(&fb),
			(bool)(sizeof(ptrdiff_t) > sizeof(u32)));
}

static void castkms_format_test_packed_vertical_step(struct kunit *test)
{
	static const struct {
		u32 format;
		unsigned int bits_per_pixel;
	} cases[] = {
		{ DRM_FORMAT_R1, 1 },
		{ DRM_FORMAT_R2, 2 },
		{ DRM_FORMAT_R4, 4 },
	};

	for (size_t i = 0; i < ARRAY_SIZE(cases); i++) {
		struct castkms_plane_state plane;
		struct castkms_frame_info frame_info;
		struct iosys_map map[DRM_FORMAT_MAX_PLANES];
		struct drm_framebuffer fb;
		struct pixel_argb_u16 pixels[3];
		pixel_read_line_t read_line;
		u16 first_level = 0xffff / ((1 << cases[i].bits_per_pixel) - 1);
		u8 data[7];
		u8 *base = data;

		memset(data, 0xa5, sizeof(data));
		base[0] = 1 << (8 - cases[i].bits_per_pixel);
		base[3] = ((1 << cases[i].bits_per_pixel) - 1) <<
			   (8 - cases[i].bits_per_pixel);
		base[6] = 0;

		castkms_format_test_init_plane(&plane, &frame_info, map, &fb,
					       cases[i].format);
		fb.pitches[0] = 3;
		iosys_map_set_vaddr(&map[0], base);

		read_line = castkms_get_pixel_read_line_function(cases[i].format);
		KUNIT_ASSERT_NOT_NULL(test, read_line);
		read_line(&plane, 0, 0, READ_TOP_TO_BOTTOM, ARRAY_SIZE(pixels),
			  pixels);

		KUNIT_EXPECT_EQ(test, pixels[0].r, first_level);
		KUNIT_EXPECT_EQ(test, pixels[1].r, (u16)0xffff);
		KUNIT_EXPECT_EQ(test, pixels[2].r, (u16)0);

		read_line(&plane, 0, 2, READ_BOTTOM_TO_TOP, ARRAY_SIZE(pixels),
			  pixels);
		KUNIT_EXPECT_EQ(test, pixels[0].r, (u16)0);
		KUNIT_EXPECT_EQ(test, pixels[1].r, (u16)0xffff);
		KUNIT_EXPECT_EQ(test, pixels[2].r, first_level);
	}
}

static void castkms_format_test_unaligned_rgb565_read(struct kunit *test)
{
	static const struct {
		u32 format;
		u16 red;
		u16 blue;
	} cases[] = {
		{ DRM_FORMAT_RGB565, 0xffff, 0 },
		{ DRM_FORMAT_BGR565, 0, 0xffff },
	};
	struct castkms_plane_state plane;
	struct castkms_frame_info frame_info;
	struct iosys_map map[DRM_FORMAT_MAX_PLANES];
	struct drm_framebuffer fb;
	struct pixel_argb_u16 pixel;
	pixel_read_line_t read_line;
	u8 source[] = { 0xa5, 0x00, 0xf8, 0xa5 };

	for (size_t i = 0; i < ARRAY_SIZE(cases); i++) {
		castkms_format_test_init_plane(&plane, &frame_info, map, &fb,
					       cases[i].format);
		fb.pitches[0] = 2;
		fb.offsets[0] = 1;
		iosys_map_set_vaddr(&map[0], source);

		read_line = castkms_get_pixel_read_line_function(cases[i].format);
		KUNIT_ASSERT_NOT_NULL(test, read_line);
		read_line(&plane, 0, 0, READ_LEFT_TO_RIGHT, 1, &pixel);
		KUNIT_EXPECT_EQ(test, pixel.r, cases[i].red);
		KUNIT_EXPECT_EQ(test, pixel.g, (u16)0);
		KUNIT_EXPECT_EQ(test, pixel.b, cases[i].blue);
	}
}

static void castkms_format_test_unaligned_rgb64_read(struct kunit *test)
{
	static const struct {
		u32 format;
		struct pixel_argb_u16 expected;
	} cases[] = {
		{ DRM_FORMAT_ARGB16161616,
		  { 0xdef0, 0x9abc, 0x5678, 0x1234 } },
		{ DRM_FORMAT_ABGR16161616,
		  { 0xdef0, 0x1234, 0x5678, 0x9abc } },
		{ DRM_FORMAT_XRGB16161616,
		  { 0xffff, 0x9abc, 0x5678, 0x1234 } },
		{ DRM_FORMAT_XBGR16161616,
		  { 0xffff, 0x1234, 0x5678, 0x9abc } },
	};
	struct castkms_plane_state plane;
	struct castkms_frame_info frame_info;
	struct iosys_map map[DRM_FORMAT_MAX_PLANES];
	struct drm_framebuffer fb;
	struct pixel_argb_u16 pixel;
	pixel_read_line_t read_line;
	u8 source[] = {
		0xa5, 0x34, 0x12, 0x78, 0x56,
		0xbc, 0x9a, 0xf0, 0xde, 0xa5,
	};

	for (size_t i = 0; i < ARRAY_SIZE(cases); i++) {
		castkms_format_test_init_plane(&plane, &frame_info, map, &fb,
					       cases[i].format);
		fb.pitches[0] = 8;
		fb.offsets[0] = 1;
		iosys_map_set_vaddr(&map[0], source);

		read_line = castkms_get_pixel_read_line_function(cases[i].format);
		KUNIT_ASSERT_NOT_NULL(test, read_line);
		read_line(&plane, 0, 0, READ_LEFT_TO_RIGHT, 1, &pixel);
		KUNIT_EXPECT_EQ(test, pixel.a, cases[i].expected.a);
		KUNIT_EXPECT_EQ(test, pixel.r, cases[i].expected.r);
		KUNIT_EXPECT_EQ(test, pixel.g, cases[i].expected.g);
		KUNIT_EXPECT_EQ(test, pixel.b, cases[i].expected.b);
	}
}

static void castkms_format_test_unaligned_rgb565_write(struct kunit *test)
{
	struct pixel_argb_u16 pixel = {
		.a = 0xffff,
		.r = 0xffff,
	};
	pixel_write_t write_pixel;
	u8 destination[] = { 0xa5, 0xa5, 0xa5, 0xa5 };

	write_pixel = castkms_get_pixel_write_function(DRM_FORMAT_RGB565);
	KUNIT_ASSERT_NOT_NULL(test, write_pixel);
	write_pixel(destination + 1, &pixel);
	KUNIT_EXPECT_EQ(test, destination[1], (u8)0x00);
	KUNIT_EXPECT_EQ(test, destination[2], (u8)0xf8);
}

static void castkms_format_test_unaligned_rgb64_write(struct kunit *test)
{
	static const struct {
		u32 format;
		u8 expected_alpha[2];
	} cases[] = {
		{ DRM_FORMAT_ARGB16161616, { 0xf0, 0xde } },
		{ DRM_FORMAT_XRGB16161616, { 0xff, 0xff } },
	};
	struct pixel_argb_u16 pixel = {
		.a = 0xdef0,
		.r = 0x9abc,
		.g = 0x5678,
		.b = 0x1234,
	};
	pixel_write_t write_pixel;
	u8 destination[10];

	for (size_t i = 0; i < ARRAY_SIZE(cases); i++) {
		memset(destination, 0xa5, sizeof(destination));
		write_pixel = castkms_get_pixel_write_function(cases[i].format);
		KUNIT_ASSERT_NOT_NULL(test, write_pixel);
		write_pixel(destination + 1, &pixel);
		KUNIT_EXPECT_EQ(test, destination[1], (u8)0x34);
		KUNIT_EXPECT_EQ(test, destination[2], (u8)0x12);
		KUNIT_EXPECT_EQ(test, destination[3], (u8)0x78);
		KUNIT_EXPECT_EQ(test, destination[4], (u8)0x56);
		KUNIT_EXPECT_EQ(test, destination[5], (u8)0xbc);
		KUNIT_EXPECT_EQ(test, destination[6], (u8)0x9a);
		KUNIT_EXPECT_EQ(test, destination[7], cases[i].expected_alpha[0]);
		KUNIT_EXPECT_EQ(test, destination[8], cases[i].expected_alpha[1]);
	}
}

static void castkms_format_test_unaligned_le16_yuv(struct kunit *test)
{
	static const u32 formats[] = {
		DRM_FORMAT_P010,
		DRM_FORMAT_P012,
		DRM_FORMAT_P016,
	};
	static const u16 sample_masks[] = {
		0xffc0,
		0xfff0,
		0xffff,
	};
	u8 luma[] = { 0xa5, 0x34, 0x12 };
	u8 chroma[] = { 0xa5, 0x78, 0x56, 0xbc, 0x9a };

	for (size_t i = 0; i < ARRAY_SIZE(formats); i++) {
		struct castkms_plane_state plane;
		struct castkms_frame_info frame_info;
		struct iosys_map map[DRM_FORMAT_MAX_PLANES];
		struct drm_framebuffer fb;
		struct conversion_matrix *matrix = &plane.conversion_matrix;
		enum drm_color_encoding encoding = DRM_COLOR_YCBCR_BT601;
		enum drm_color_range range = DRM_COLOR_YCBCR_FULL_RANGE;
		struct pixel_argb_u16 expected;
		struct pixel_argb_u16 pixel;
		pixel_read_line_t read_line;
		u16 y = 0x1234 & sample_masks[i];
		u16 u = 0x5678 & sample_masks[i];
		u16 v = 0x9abc & sample_masks[i];

		castkms_format_test_init_plane(&plane, &frame_info, map, &fb,
					       formats[i]);
		fb.pitches[0] = 2;
		fb.pitches[1] = 4;
		fb.offsets[0] = 1;
		fb.offsets[1] = 1;
		iosys_map_set_vaddr(&map[0], luma);
		iosys_map_set_vaddr(&map[1], chroma);
		castkms_get_conversion_matrix_to_argb_u16(formats[i], encoding,
							  range, matrix);

		read_line = castkms_get_pixel_read_line_function(formats[i]);
		KUNIT_ASSERT_NOT_NULL(test, read_line);
		read_line(&plane, 0, 0, READ_LEFT_TO_RIGHT, 1, &pixel);
		expected = castkms_argb_u16_from_yuv161616(matrix, y, u, v);

		KUNIT_EXPECT_EQ(test, pixel.a, expected.a);
		KUNIT_EXPECT_EQ(test, pixel.r, expected.r);
		KUNIT_EXPECT_EQ(test, pixel.g, expected.g);
		KUNIT_EXPECT_EQ(test, pixel.b, expected.b);
	}
}

/*
 * castkms_format_test_yuv_u16_to_argb_u16 - Testing the conversion between YUV
 * colors to ARGB colors in CASTKMS
 *
 * This test will use the functions castkms_get_conversion_matrix_to_argb_u16 and
 * castkms_argb_u16_from_yuv161616 to convert YUV colors (stored in
 * yuv_u16_to_argb_u16_cases) into ARGB colors.
 *
 * The conversion between YUV and RGB is not totally reversible, so there may be
 * some difference between the expected value and the result.
 */
static void castkms_format_test_yuv_u16_to_argb_u16(struct kunit *test)
{
	const struct yuv_u16_to_argb_u16_case *param = test->param_value;
	struct pixel_argb_u16 argb;

	for (size_t i = 0; i < param->n_colors; i++) {
		const struct format_pair *color = &param->colors[i];
		struct conversion_matrix matrix;

		castkms_get_conversion_matrix_to_argb_u16
			(DRM_FORMAT_NV12, param->encoding, param->range, &matrix);

		argb = castkms_argb_u16_from_yuv161616(&matrix, color->yuv.y, color->yuv.u,
					       color->yuv.v);

		KUNIT_EXPECT_LE_MSG(test, abs_diff(argb.a, color->argb.a), 0x1ff,
				    "On the A channel of the color %s expected 0x%04x, got 0x%04x",
				    color->name, color->argb.a, argb.a);
		KUNIT_EXPECT_LE_MSG(test, abs_diff(argb.r, color->argb.r), 0x1ff,
				    "On the R channel of the color %s expected 0x%04x, got 0x%04x",
				    color->name, color->argb.r, argb.r);
		KUNIT_EXPECT_LE_MSG(test, abs_diff(argb.g, color->argb.g), 0x1ff,
				    "On the G channel of the color %s expected 0x%04x, got 0x%04x",
				    color->name, color->argb.g, argb.g);
		KUNIT_EXPECT_LE_MSG(test, abs_diff(argb.b, color->argb.b), 0x1ff,
				    "On the B channel of the color %s expected 0x%04x, got 0x%04x",
				    color->name, color->argb.b, argb.b);
	}
}

static void castkms_format_test_yuv_u16_to_argb_u16_case_desc(struct yuv_u16_to_argb_u16_case *t,
							   char *desc)
{
	snprintf(desc, KUNIT_PARAM_DESC_SIZE, "%s - %s",
		 t->encoding == DRM_COLOR_YCBCR_BT601 ? "BT.601" :
		 t->encoding == DRM_COLOR_YCBCR_BT709 ? "BT.709" : "BT.2020",
		 t->range == DRM_COLOR_YCBCR_FULL_RANGE ? "full" : "limited");
}

KUNIT_ARRAY_PARAM(yuv_u16_to_argb_u16, yuv_u16_to_argb_u16_cases,
		  castkms_format_test_yuv_u16_to_argb_u16_case_desc
);

static struct kunit_case castkms_format_test_cases[] = {
	KUNIT_CASE(castkms_format_test_framebuffer_offset),
	KUNIT_CASE(castkms_format_test_distinct_multiplane_maps),
	KUNIT_CASE(castkms_format_test_wide_framebuffer_offset),
	KUNIT_CASE(castkms_format_test_stride_range),
	KUNIT_CASE(castkms_format_test_packed_vertical_step),
	KUNIT_CASE(castkms_format_test_unaligned_rgb565_read),
	KUNIT_CASE(castkms_format_test_unaligned_rgb64_read),
	KUNIT_CASE(castkms_format_test_unaligned_rgb565_write),
	KUNIT_CASE(castkms_format_test_unaligned_rgb64_write),
	KUNIT_CASE(castkms_format_test_unaligned_le16_yuv),
	KUNIT_CASE_PARAM(castkms_format_test_yuv_u16_to_argb_u16, yuv_u16_to_argb_u16_gen_params),
	{}
};

static struct kunit_suite castkms_format_test_suite = {
	.name = "castkms-format",
	.test_cases = castkms_format_test_cases,
};

kunit_test_suite(castkms_format_test_suite);

MODULE_LICENSE("GPL");
MODULE_DESCRIPTION("Kunit test for castkms format conversion");
