# SPDX-License-Identifier: GPL-2.0-only

castkms-kunit-tests-y := \
	castkms_config_test.o \
	castkms_format_test.o \
	castkms_color_test.o \
	castkms_frame_dispatch_test.o

obj-$(CONFIG_DRM_CASTKMS_KUNIT_TEST) += castkms-kunit-tests.o
