#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only

set -euo pipefail

ssh_user=${1:?missing guest user}
desktop_stamp=/var/lib/castkms-vm/desktop-v2
desktop_manifest=/var/lib/castkms-vm/desktop-packages.txt
gdm_conf=/etc/gdm/custom.conf
desktop_packages=(
	dbus-daemon
	gdm
	gnome-session-wayland-session
	gnome-settings-daemon
	gnome-shell
	gtk4-devel
	mesa-dri-drivers
	mesa-libgbm
	mesa-vulkan-drivers
	mutter
)

if test ! -e "$desktop_stamp"; then
	sudo dnf -y -q --setopt=install_weak_deps=False install \
		"${desktop_packages[@]}"
	sudo mkdir -p "$(dirname -- "$desktop_stamp")"
	sudo touch "$desktop_stamp"
fi

rpm -q --whatprovides \
	--qf '%{NAME}-%{EPOCHNUM}:%{VERSION}-%{RELEASE}.%{ARCH}\n' \
	"${desktop_packages[@]}" | LC_ALL=C sort -u | \
	sudo tee "$desktop_manifest" >/dev/null

sudo usermod -aG video,render,input "$ssh_user"
sudo passwd -d "$ssh_user"

sudo tee "$gdm_conf" >/dev/null <<EOF
# Generated by castkms-vm desktop-provision
[daemon]
WaylandEnable=true
AutomaticLoginEnable=true
AutomaticLogin=$ssh_user
EOF

sudo systemctl set-default graphical.target
sudo systemctl enable gdm.service
sudo systemctl disable --now gnome-initial-setup-first-login.service \
	2>/dev/null || true

# The unit is refreshed again after sync; enable it now so a later reboot
# re-attaches once the module and capture tool exist on disk.
repo_dir=/home/"$ssh_user"/castkms
if test -f "$repo_dir/scripts/vm/castkms-attach.service" &&
	test -x "$repo_dir/scripts/vm/guest-attach-monitor.sh"; then
	sudo install -m 0755 "$repo_dir/scripts/vm/guest-attach-monitor.sh" \
		/usr/local/libexec/castkms-attach-monitor
	if test -r "$repo_dir/scripts/vm/module-dependencies.sh"; then
		sudo install -m 0644 "$repo_dir/scripts/vm/module-dependencies.sh" \
			/usr/local/libexec/castkms-module-dependencies
	fi
	if test -x "$repo_dir/tools/castkms-attach"; then
		sudo install -m 0755 "$repo_dir/tools/castkms-attach" \
			/usr/local/libexec/castkms-attach
	fi
	if test -x "$repo_dir/tools/castkms-grant-launch"; then
		sudo install -m 0755 "$repo_dir/tools/castkms-grant-launch" \
			/usr/local/libexec/castkms-grant-launch
	fi
	if test -f "$repo_dir/castkms.ko"; then
		sudo mkdir -p /usr/local/lib/castkms
		sudo install -m 0644 "$repo_dir/castkms.ko" \
			/usr/local/lib/castkms/castkms.ko
	fi
	sudo install -m 0644 "$repo_dir/scripts/vm/castkms-attach.service" \
		/etc/systemd/system/castkms-attach.service
	sudo systemctl daemon-reload
	sudo systemctl enable castkms-attach.service
fi

printf 'desktop_user=%s\n' "$ssh_user"
printf 'graphical_target=%s\n' "$(systemctl get-default)"
printf 'gdm_enabled=%s\n' "$(systemctl is-enabled gdm.service)"
printf 'desktop_manifest=%s\n' "$desktop_manifest"
