/* SPDX-License-Identifier: GPL-2.0+ */

#ifndef _CASTKMS_LIMITS_H_
#define _CASTKMS_LIMITS_H_

#define CASTKMS_DEFAULT_DEVICE_NAME "castkms"

#define CASTKMS_MIN_WIDTH 10U
#define CASTKMS_MIN_HEIGHT 10U

#define CASTKMS_DEFAULT_WIDTH 1024
#define CASTKMS_DEFAULT_HEIGHT 768

#define CASTKMS_MAX_WIDTH 8192U
#define CASTKMS_MAX_HEIGHT 8192U

#define CASTKMS_MAX_CURSOR_WIDTH 512U
#define CASTKMS_MAX_CURSOR_HEIGHT 512U
#define CASTKMS_MAX_EDID_SIZE 512U

#define CASTKMS_NUM_OVERLAY_PLANES 8
#define CASTKMS_MAX_OUTPUT_OBJECTS 31

#endif /* _CASTKMS_LIMITS_H_ */
